### ISSUE TITLE
翻譯問題

### ISSUE THREAD

**Issue by louis70109** [doggy8088/typescript-tutorial#1]
保哥，下面介紹的 "形狀" 是要翻譯成 "型態" 或 "型別" 嗎？
https://willh.gitbook.io/typescript-tutorial/basics/type-of-object-interfaces#ke-xuan-shu-xing

**Comment by doggy8088** [comment]
沒有翻錯，原文就是 "Shape"

本文一開始就有提到「物件的形狀（Shape）」，講的就是物件中應該有哪些屬性。
