### ISSUE TITLE
interface的介紹有誤? 

### ISSUE THREAD

**Issue by tooilxui** [doggy8088/typescript-tutorial#3]
https://github.com/doggy8088/typescript-tutorial/blob/master/basics/type-of-object-interfaces.md
上面這個連結的內文描述：

> 定義的變數比介面少了一些屬性是不允許的：
多一些屬性也是不允許的：
可見，賦值的時候，變數的形狀必須和介面的形狀保持一致。

但事實上官網明明是允許的?  https://www.typescriptlang.org/docs/handbook/interfaces.html

>  but the compiler only checks that at least the ones required are present and match the types required

**Comment by doggy8088** [comment]
你說的那一段，是比介面多一個屬性，不是少一個屬性。
